name: AWS Service CI/CD

on:
  push:
    branches: [consig*]

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/cdk-deploy.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    with:
      stack: jambonzApiServer
